version: "3.9"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      AWS_REGION: eu-west-1
      AWS_ENDPOINT: http://localstack:4566
      AWS_SQS_IN_QUEUE_URL: http://localstack:4566/000000000000/sqs1
      AWS_SQS_OUT_QUEUE_URL: http://localstack:4566/000000000000/sqs2
    depends_on:
      - localstack

  localstack:
    image: localstack/localstack:latest
    environment:
      - SERVICES=sqs
      - DEFAULT_REGION=eu-west-1
    ports:
      - "4566:4566"