spring:
  datasource:
    url: jdbc:h2:mem:challenge;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1
    username: local
    password: local
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.time_zone: UTC
  h2:
    console:
      enabled: true

logging:
  level:
    org.hibernate.SQL: warn

app:
  auth:
    base-url: http://localhost:8080
    whitelist: [1, 2, 3, 42]

aws:
  region: eu-west-1
  endpoint: http://localhost:4566
  sqs:
    in-queue-url: http://localhost:4566/000000000000/sqs1
    out-queue-url: http://localhost:4566/000000000000/sqs2