spring:
  datasource:
    url: jdbc:h2:mem:challenge;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.time_zone: UTC
  h2:
    console:
      enabled: true

logging:
  level:
    org.hibernate.SQL: warn